class Langs(object):
	messages = {
		"validating_bombcrypto_bot_account": "Validating BombCrypto Bot account",
		"lost_connection": "Lost connection to BombCrypto Bot validation servers",
		"unlocking_wallet": "Unloking MetaMask wallet",
		"connecting_wallet": "Connecting MetaMask wallet to the game",
		"page_didnt_load": "Page didn't load', restarting!",
		"page_loaded_bot_ready": "Page loaded, Bot is ready to start",
		"wallet_unlocked": "Wallet unlocked",
		"bnb_symbol_found": "BNB Symbol found, page may has been restarted to avoid any buggy connection!",
		"restart_after_unlock": "Page restarted, the game is ready to connect!",
		"metamask_didnt_open": "Didn't found any confirmation of metamask opened, needs to restart! (Try to use BNB Waiting 60 sec, -bw 60)",
		"metammask_sign_login": "Siging metamask login",
		"something_wrong": "Something went wrong, restarting!",
		"end_work": "Enough work for the day",
		"new_map": "New map appeared!",
		"sending_heroes_work": "Sending heros to work",
		"all_heroes_ready": "All heroes are ready to work",
		"working": "At cave working, waiting few minutes...",
		"anti_bot_detected": "Captcha detected, solving",
		"waiting_bnb_symbol": "Waiting you connect your wallet, bot will resume after find BNB Symbol.",
		"captcha_force_miss": "Captcha will be wrong to miss humam behaviours.",
		"account_valid": "Account validated! X instances valid until: Y (America/Sao Paulo)",
		"captcha_expected": "Expected captcha to find:",
		# Launcher
		"version": "Version",
		"exit": "Exit",
		"license_key": "License Key",
		"farmin_options": "Farming Options",
		"min_hero_stam": "Minimum hero stamina to send work:",
		"min_hero_stam_time": "Minutes between test hero stamina:",
		"mins_pathfind": "Minutes between pathfind renew:",
		"save_maps": "Save new maps?",
		"no": "No",
		"yes": "Yes",
		"minutes_chest": "Minutes between chest click:",
		"start_bot": "Start BombCryptoBot",
		"other_options": "Other Options",
		"login_error": "Login erros to trigger waiting:",
		"waiting_time_login_error": "Waiting time after trigger login error:",
		"waiting_bnb_txt": "Waiting BNB time:",
		"more": "More",
		"sec": "Sec",
		"times": "Times",
		"instance_box": "Instance Name",
		# Errors
		"error_validation_bombcrypto_bot": "Your account could not be validated, please check your key at config.json",
		"error_connection": "Your account could not be validated due connection issue, this is the #x time, bot will close at 3x time.",
		"error_code": "Error code",
		"error": "Error",
		"error_loading_stuck": "Loading stuck error detected!",
		"error_login": "Login error detected!",
		"error_bar": "General error bar detected!",
		"error_renewing_pathfind": "Error renewing hero's pathfinder",
		"error_loading_hero_list": "Can't load hero list, restarting!",
		"error_scrolling_page": "Failed to scroll down hero's list",
		"error_critical": "Something critical happened on the runtime",
		"error_captcha_decode": "Can't find the piece location for captcha, restarting",
		"error_bypass_failed": "Captcha bypass failed, trying again",
		"error_login_waiting": "Maximum consecultive logins erros, waiting before resuming.",
		"error_captcha_front": "Could not decode what numbers captcha need, retrying",
		"error_login_restarted": "Something restarted the page, reloading Bot.",
		'error_no_instance_name': "No instance name defined.",
		"error_no_chromedriver": "Chromedriver not found, please download chromedriver to your chrome version and extract it to Bot folder."
	}
