class Langs(object):
	messages = {
		"validating_bombcrypto_bot_account": "Validano conta do BombCrypto Bot",
		"lost_connection": "Perda de conexão com os servidores de validação do BombCrypto Bot",
		"unlocking_wallet": "Desbloqueando caretira MetaMask",
		"connecting_wallet": "Connectando carteira MetaMask ao jogo",
		"page_didnt_load": "A página não carregou, atualizando!",
		"page_loaded_bot_ready": "Página carregada, o Bot está pronto para começar",
		"wallet_unlocked": "Carteira desbloqueada",
		"bnb_symbol_found": "Simbolo BNB encontrado, atualizando a página para corrigir qualquer bug de conexão!",
		"restart_after_unlock": "Página atualizada, o jogo está pronto para conectar!",
		"metamask_didnt_open": "Não foi encontrada nenhuma confirmação do MetaMask ter aberto, precisamos atualizar a página! (Tente usar a espera pelo simbolo BNB em 60 segundos, -bw 60)",
		"metammask_sign_login": "Assinando o login MetaMask",
		"something_wrong": "Alguma coisa de errado aconteceu, atualizando a página!",
		"end_work": "Chega de trabalho por hora",
		"new_map": "Um novo mapa apareceu!",
		"sending_heroes_work": "Enviando herois para o trabalho",
		"all_heroes_ready": "Todos os herois estão prontos para trabalhar",
		"working": "Na cavera trabalhando, esperando alguns minutos...",
		"anti_bot_detected": "Captcha detectado, resolvendo",
		"waiting_bnb_symbol": "Aguardando você conectar a conta MetamMask, o bot vai continuar quando encontrar o simbolo BNB.",
		"captcha_force_miss": "O captcha vai ser errado para imitar o comportamento humano.",
		"account_valid": "Conta validada! X instâncias válidas até: Y",
		"captcha_expected": "Captcha a ser encontrado:",
		# Launcher
		"version": "Versão",
		"exit": "Sair",
		"license_key": "Chave de licença",
		"farmin_options": "Opções de Farm",
		"min_hero_stam": "Mim. energia para trabalhar:",
		"min_hero_stam_time": "Mins. para testar energia:",
		"mins_pathfind": "Mins. para renovar a localização:",
		"save_maps": "Salvar novos mapas?",
		"no": "Não",
		"yes": "Sim",
		"minutes_chest": "Mins. entre clicar na chest:",
		"start_bot": "Inciar o BombCryptoBot",
		"other_options": "Outras Opções",
		"login_error": "Erros de login para começar espera:",
		"waiting_time_login_error": "Tempo de espera apos erros de login:",
		"waiting_bnb_txt": "Tempo esperando o símbolo da BNB:",
		"more": "Mais",
		"sec": "Seg",
		"times": "Vezes",
		"instance_box": "Nome da instância",
		# Errors
		"error_validation_bombcrypto_bot": "Sua conta não pode ser validada, por favor verifique sua chave no config.json",
		"error_connection": "Sua conta não pode ser validada por conta de problemas de conexão, este é o #o erro, o bot será fechado no 3o erro.",
		"error_code": "Código do erro",
		"error": "Erro",
		"error_loading_stuck": "Travado na tela de login!",
		"error_login": "Erro de login!",
		"error_bar": "Barra de erro detectada, atualizando a página!",
		"error_renewing_pathfind": "Erro renovando a localização dos herois no mapa",
		"error_loading_hero_list": "Não foi possível carregar a lista de herois, atualizando a página!",
		"error_scrolling_page": "Não foi possível scrollar a tela de herois",
		"error_critical": "Algo crítico aconteceu na execução.",
		"error_captcha_decode": "Não foi possível encontrar o local da peça para este captcha, atualizando a página",
		"error_bypass_failed": "Não foi possível quebrar este captcha, tentando novamente",
		"error_login_waiting": "Máximo de erros de login consecultivos, esperando antes de tentar de novo.",
		"error_captcha_front": "Não conseguimos decodificar os numeros do captcha, tentando novamente",
		"error_login_restarted": "Algo atualizou a página, religando o Bot.",
		'error_no_instance_name': "Nome da instância não definido.",
		"error_no_chromedriver": "Chromedriver não encontrado, faço o download do chromedriver para a versão do seu chrome e extria na pasta do Bot."
	}
